### ISSUE TITLE
No sabemos como usar Terraform con Azure

### ISSUE THREAD

**Issue by ryepesg** [DevSeCol/test1#2]

**Comment by servas1** [comment]
Prueba de cómo usar un issue

**Comment by servas1** [comment]
- Descargar la herramienta terraform
- Entender que es terraform
- Entender que es un manejador de nubes
- Escoger a azure como nube a manejar
- Escogi visual estudio code como herramienta
- Seleccione plugins terraform con azurre
- Realizar la conexion con azure
      - https://docs.microsoft.com/en-us/azure/developer/terraform/install-configure
-Crear un resource group
